### ISSUE TITLE
Hooks not firing on embedded admins (e.g. using sonata_type_admin to embed another Admin)

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1502]
For example, I have a `Document` class and an `Image` class. In `ImageAdmin` I have `prePersist()` and `preUpdate()` methods to handle the saving of the uploaded files.

This works fine when I'm editing Images directly via SonataAdmin. The save hooks fire and all is well.

In `DocumentAdmin` I use `sonata_type_admin` as the field type to embed the `ImageAdmin` form:

``` php
    class DocumentAdmin extends Admin
    {
        $formMapper
            ...
            ->add('imageHeader', 'sonata_type_admin')
            ...
        ;
    }
```

But when I upload a new image file from the Document edit page in SonataAdmin it does not fire the save hooks for the embedded `ImageAdmin`.

Now, I know that I could probably put some code into `DocumentAdmin::prePersist()` and `DocumentAdmin::preUpdate()` but this doesn't seem very DRY (and feels like something that the SonataAdminBundle should be doing for me when I embed another Admin class using sonata_type_admin).

Have I just misconfigured something or is the non-propagation of save hooks something that we need to look into coding into this bundle in future?

**Comment by bobemoe** [comment]
Exact same issue here as the Document and Image example..  Has this been solved yet? Thanks.

**Comment by bobemoe** [comment]
OK, i found another discussion:
https://github.com/sonata-project/SonataAdminBundle/issues/1400
which leads to some documentation and an example:
https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_file_uploads.html#advanced-example-works-with-embedded-admins

**Comment by ibasaw** [comment]
how to solve this ? neeed prePersist() and preUpdate() in my collections sub forms

**Comment by chalasr** [comment]
:+1: This issue still exists, hooks of embedded admin classes are not fired.

There is a quick-and-dirty(-and-ugly) alternative that consists in calling the child admin's hooks from the parent class.

For instance, if you have a Post admin that have a Comment field as embedded admin class, and you want do stuff on `CommentAdmin::prePersist()`:

```php
// PostAdmin (parent)
public function prePersist($post)
{
    $commentAdmin = $this
        ->getConfigurationPool()
        ->getAdminByAdminCode('comment_admin_service_id');

    foreach ($post->getComments as $comment) {
        $commentAdmin->prePersist($comment); 
    }
}

**Comment by quisse** [comment]
This issue still seems to exist.
My solution is as follows in the parent admin:
   
    public function prePersist($object)
    {
        parent::prePersist($object);
    
        foreach ($this->getFormFieldDescriptions() as $fieldName => $fieldDescription) {
            // detect embedded Admins
            if ($fieldDescription->getType() === AdminType::class) {
                /** @var AbstractAdmin $associationAdmin */
                $associationAdmin = $fieldDescription->getAssociationAdmin();
                $object = $associationAdmin->getSubject();
                $associationAdmin->prePersist($object);
            }
        }
    }

I am willing to create a PR to get this in the `AbstractAdmin` class if there's no reason this shouldn't be there.

**Comment by RaphaelBuquet** [comment]
prePersist() is not called either. I'm assuming that it would be a bit trickier to implement.

**Comment by icedevelopment** [comment]
This bug is still happening on 3.57.0 and the workaround proposed by @chalasr doesn't seem to work with `preRemove`.

**Comment by VincentLanglet** [comment]
I understand the issue but I also feel like this is somehow a mis-understanding of the AdminType.
The AdminType is not really an admin but a FormType before everything else.

This is a simple way to generate a form, 
- The `getNewInstance` method is used to generate a new object
- The `getFormBuilder` method is used to generate the form
But that's all.

I assume none of you used a custom ModelManager, but if you override the `ModelManager::create/update` method instead of adding code inside `prePersist/preUpdate` you'll see, the modelManager method of the "embedded admin" is not called. All the logic is let to the form component
```
$form = $this->admin->getForm();
$form->setData($newObject);
$form->handleRequest($request);
$newObject = $this->admin->create($submittedObject);
```

For prePersist/preUpdate/preRemove hooks related to an admin, you may rely on a persistence parameter in the url ; for instance `/admin/image/create?fullWidth=1` or `/admin/document/42/image/create?fullWidth=1`. If you're on a document creation, `/admin/document/create` you won't have the persistence parameter (since it's only on imageAdmin) and the related prePersist/preUpdate/preRemove  hooks could ends up with weird behavior.
So I won't consider it's should be automatically called. If it should be, you should use Doctrine entityListeners instead.

Moreover since Sonata 4, calling pre* hooks makes less sens and are less possible now that those methods are protected.

I think we should close this @jordisala1991 wdyt ?

**Comment by jordisala1991** [comment]
I agree, lets close. An issue 9 years old is not really useful anyway.

**Comment by shkkmo** [comment]
> I understand the issue but I also feel like this is somehow a mis-understanding of the AdminType.
The AdminType is not really an admin but a FormType before everything else.

It is a FormType that stores a referrence to an embedded admin instance. What is the misunderstanding? If you try to get the embedded admin instance via the service ID, you will get the wrong instance and which will not have any awareness of your parent field description. 

> if you override the ModelManager::create/update method instead of adding code inside prePersist/preUpdate you'll see, the modelManager method of the "embedded admin" is not called. All the logic is let to the form component

This seems like a mistake. Why wouldn't you call the associated methods of the embedded admin's model manager? It seems like the create, update and delete methods should be called on embedded admin instances. That would solve both issues.

> So I won't consider it's should be automatically called. If it should be, you should use Doctrine entityListeners instead.

Then why have the admin lifecycle callbacks at all? If you have them, they should be called automatically for embedded and non-embedded admins alike.

>  If you're on a document creation, /admin/document/create you won't have the persistence parameter (since it's only on imageAdmin) and the related prePersist/preUpdate/preRemove hooks could ends up with weird behavior.

If you are parsing the url/parameters in your lifecycle hooks (which to me seems like the wrong place to do that), it is up to you to do that correctly (by perhaps making that parsing contingent on the result of calling 'hasParentFieldDescription';

> Moreover since Sonata 4, calling pre* hooks makes less sens and are less possible now that those methods are protected.

This just makes this issue harder to work around, not less likely to occur.

The problem with fixing this like it should be, is that there doesn't appear to be a clean way of determining where we are in the lifecycle for objects in embedded admins since this is currently determined for top level admins by the controller action.
