### ISSUE TITLE
Documentation: time to clean up and extend the SonataAdmin docs

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1519]
I've discussed this with @rande and @lsmith77 and I'm going to volunteer to take point on bringing the Sonata docs up to date and organising the addition of cookbook recipes to the SonataAdmin documentation. I'm uniquely qualified to do this since I'm new to SonataAdmin and don't know how it works (yet)!

There are three areas that need attention:
1. ensure that the existing manual is up to date and easy to read
2. add manual sections for any undocumented basic functionality
3. add cookbook style "how to" recipes for more complex use-cases

I will post separate issues here on github for each existing manual page that needs attention, each area of functionality that I know needs documentation and each recipe that needs a (volunteer) chef.
## How can you help?

**Get involved!** There are lots of ways to help:
- If you know a bit about how SonataAdmin works then take on some of the issues posted and try to solve them.
- If you are new to Sonata and there's something you don't understand or you feel is not documented well, leave a comment below (in this thread). I'll review it and add a related issue if needed.
- If you have a website or internal wiki that already has some cookbook entries then you're in a great position to squash an issue or two. Either make a formal PR or just send me the text and then get a warm and fuzzy feeling inside for helping the whole community. 

If you're not sure how to make a PR, are not a native english speaker or don't know how to write rst docs that is not a problem. **_And definitely not an excuse_ ;)** Just send me the information in whatever format you can (e.g. a hyperlink, a word doc in broken english, I'll even take a crack at source material in French or Spanish) and I'll do what I can to reformat it into documentation that can be published for the benefit of the whole community. My Twitter handle and a sonata-specific email address are below.

If you want I can mention your handle or company name in the issue with a quick "thank you" (and maybe even tweet a thank you that mentions you) but you won't get a mention in the docs themselves, which are all basically anonymous.
## When is _this_ issue closed?

Docs evolve and grow forever, but individual issues are made to be solved and closed. Once we've gone through and brought the existing manual up to date, added key missing documentation for existing features and built a reasonable cookbook it will be time to close this particular issue and celebrate.

Keep your eyes peeled for the individual issues and I look forward to your responses!

Christian
@h4ppydotcom on twitter
sonata-docs á caponica dotcom

**Comment by webdevilopers** [comment]
My commit for (default) filter usage has been merged. Please feel free to have a look.

Looking forward for the export docs @krewetka ! :+1:

**Comment by tbyte80** [comment]
I spent quite a bit of time understanding how the wiring between entities works. If you have the type "entity" (like mentioned on the "Getting Started" page) you have to specify a target class but if you want to use a type like "sonata_type_model" or "sonata_type_model_list" the target class is determined automatically. I had a bit of trouble finding out **how the magic works**.

Of course it's not really magic because (using doctrine ORM) the table metadata is used to determine the wired entity but this is not documented very well. The metadata of my tables were reverse engineered by doctrine using existing MyISAM tables so no relation information could be derived automatically. When I added the missing information (e.g. many-to-one relations) to the metadata and the respective entities, everything worked like a charm.

Another note on that topic "https://sonata-project.org/bundles/doctrine-orm-admin/2-2/doc/reference/form_field_definition.html" maybe under "6.1 Example" would be nice. (e.g. "Note: When using types like "sonata_type_model" the target entity is determined automatically. In order to do that the respective relations must be defined properly in your entity annotations or xml/yml Doctrine config files.")
