### ISSUE TITLE
Creating custom data listing in Sonata Admin

### ISSUE THREAD

**Issue by MeuhMeuh** [sonata-project/SonataAdminBundle#1734]
Hello,

I am currently trying to create custom lists data that are not always related to entities.
In order to do that, I imagined I had to : 
1) First, extend CRUDController to implement my own actions,
2) Implement my new routers thanks to configureRoutes() method override in my Admin class,
3) Define in my action what data to display and how to render it. The problem is actually here : I wanted to use the listing system of SonataAdmin (as for the generated lists by default), and to get my inspiration from CRUDController::listAction() method, but I don't know how to handle my data so that I can pass it to the list template. How can I do that?

I also have to say that I am forced to use that way because I want to display custom data in a column of my list that is quite different from "original" date from my entity. I have a "Campaign" entity and I want to list all the campaigns, but in the display I also want to show a value that I would get from a query. I guess it's the only way to do it (defining a new action), am I right?

Thank you !

**Comment by blaues0cke** [comment]
@MeuhMeuh Did you found a solution? Got a similar issue here.

**Comment by MeuhMeuh** [comment]
Hey,

Sorry for the (very) late answer, I kinda forgot to update it. I couldn't get a proper solution to use at that time and I didn't try your solution, @webdevilopers because yours came up a few months after mine. It would be interesting to see if it can fix yours @blaues0cke , but I stopped working on the project I was working on when using Sonata so I can't really relate to my previous solution.

Good luck !

**Comment by webdevilopers** [comment]
Actually it doesn't sound that hard. Non-mapped fields for entity can be achieved by edding `getters` to the Entity that will pass the value to a custom template:

**Entity**:
```php
class Contract
{
   /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\ContractState", mappedBy="contract")
     * @ORM\OrderBy({"date" = "DESC"})
     */
    private $states;
 
    public function getCurrentState()
    {
        return 'pending';
    }
}
```

**Admin Class**:
```php
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('options', 'string', array(
                'template' => 'AppContractBundle:ContractAdmin:list__state.html.twig'
            ))
        ;
    }
```

**Template:**
```twig
# Resources/views/ContractAdmin/list__state.html.twig
 
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
 
{% block field %}
    {{ object.currentState }}
{% endblock %}
```

Then create some custom actions with custom variables (`link_parameters`).
Then in your Admin Class you receive the `Request` object and dynamically `add` or hide list columns.

**Comment by blaues0cke** [comment]
Ok, thats cool. In my case I got a competition bundle and I wanted to display a list of competition winners after the user clicked on my custom action button without storing them as entities in my database since is not required to store the generated data at all. After a lot of research I resigned with the fact that it is not that easy to generate custom list views without ORM in the background, so I decided to store it in the database.

So I think my problem is no longer related to this issue since my custom action and the list is working.

But it would be great to got the possibiliy to generate list views with static data, do you know a solution for this?

**Comment by webdevilopers** [comment]
Not sure what you mean by "static data" since every data is stored somewhere, right?

What I like to do is collect data from my database (e.g. SUM, COUNT, GROUP queries etc.) to get some "read-only" archive data and then store it inside a MongoDB Collection.

Then I use the `SonataDoctrineMongoDBAdmin` to select the data from my document collections inside the Sonata list view.

**Comment by blaues0cke** [comment]
When I think about it... you are right... all the data I want to display are stored in databases. Me stupid :+1:

**Comment by MeuhMeuh** [comment]
Glad you could find a solution !

**Comment by chakiri** [comment]
to customise the listField of sonata you should override Model/UserAdmin into your own bundle, and then add a function createQuery with your queryBuilder 

```
namespace AppBundle\Admin;

use ...

class UserAdmin extends SonataUserAdmin
{
     protected function configureFormFields(FormMapper $formMapper): void
     {
        parent::configureFormFields($formMapper);
        ...
     }

     //Here an exemple of a condition
     public function createQuery($context = 'user')
     {
        $query = parent::createQuery($context);
        $query->getQueryBuilder()
            ->select('o')
            ->where('o.isRemoved is NULL')
        ;
        dump($query->execute());
        return $query;
    }
}
```
