### ISSUE TITLE
How to filter a number by range or comparison?

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1891]
I'm back on Sonata again and setting up a new admin. Will work on the docs again when I get a chance!

In the meantime, I'm completely stuck with trying to add a filter that will either 
(a) let me show a comparison box (<, >, >=, etc) and a field to enter a value, or
(b) show two boxes so I can enter two numbers to search between

There's no information in the [url=http://sonata-project.org/bundles/admin/master/doc/reference/action_list.html]SonataAdmin list docs[/url] and the [url=http://sonata-project.org/bundles/doctrine-orm-admin/master/doc/reference/filter_field_definition.html]DoctrineOrmAdmin docs[/url] are questionable, e.g. they suggest that `doctrine_orm_model` depends on `sonata_type_filter_number` (which looks wrong to me, but I guess it could be right) and say that there are no date filters yet (even though they seem to work fine).

If somebody could post a quick example of how to set up either (or both) of the filter types mentioned above then I'll commit to writing it up properly and adding it to the SonataAdmin docs!

**Comment by yurtesen** [comment]
Well so the documentation says `doctrine_orm_model: depends on the sonata_type_filter_number Form Type,` [at this page ](https://sonata-project.org/bundles/doctrine-orm-admin/master/doc/reference/filter_field_definition.html) but it should actually be `doctrine_orm_number`

I just wonder why it was not fixed since 2014 😄 ???

**Comment by core23** [comment]
Feel free to fix this @yurtesen

**Comment by yurtesen** [comment]
@core23 If I knew what I was doing, I wouldn't be in the documentation. 😅  The problem is, I am very new to sonata admin bundle. If you can fill in the blanks for me, I can make a PR. According to [this file](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/src/Resources/config/doctrine_orm_filter_types.xml) I propose the following changes. Agreed?

Current:
```
doctrine_orm_model: depends on the sonata_type_filter_number Form Type,
doctrine_orm_string: depends on the sonata_type_filter_choice,
doctrine_orm_number: depends on the sonata_type_filter_choice Form Type, renders yes or no field,
doctrine_orm_class: depends on the sonata_type_filter_default Form type, renders a choice list field.
```

My Proposal:
```
doctrine_orm_model: depends on the sonata_type_filter_model Form Type,
doctrine_orm_string: depends on the sonata_type_filter_string Form Type,
doctrine_orm_number: depends on the sonata_type_filter_number Form Type,
doctrine_orm_class: depends on the sonata_type_filter_class Form type, 
```
