### ISSUE TITLE
Add localization support for select2

### ISSUE THREAD

**Issue by pulzarraider** [sonata-project/SonataAdminBundle#2365]
Select2 is localized to different languages.
We need to add the correct js file based on current user locale.

**Comment by 537mfb** [comment]
In my case, the browser sends the following `accept-language` with the request:

`accept-language: pt-PT,pt;q=0.9,pt-BR;q=0.8,en;q=0.7,en-US;q=0.6,en-GB;q=0.5`

Only there's no `pt-PT.js`, and instead of defaulting to the generic `pt.js` as it should, it adds a script tag for the non existing `pt-PT.js` and that generates a `404` and no localization file is ever loaded

![Image](https://github.com/user-attachments/assets/bc76037e-ea35-41f8-a4da-1d62b276a886)

![Image](https://github.com/user-attachments/assets/4012249e-9ca5-4d4e-864d-6e4414b18dd2)

**EDIT**: whenever the user locale is in the form `xx-YY`, and there's no `xx-YY.js` file, it should check for a file named `xx.js` and if it exists use that. If neither exists, it should either get the next locale from the accept-language header (preferable) or default to `en` and load `en.js`,

**Comment by zyberspace** [comment]
Hi @537mfb ,

can you copy your comment exactly like it is into a new ticket? Maybe with the title "Select2 Localization support for Portuguese".

This issue here is from 2014 and over 10 years old.

**Comment by 537mfb** [comment]
Hi @zyberspace

You're quite right - sorry about that
New issue has been opened with this - #8280
