### ISSUE TITLE
embedded sonata_type_model_autocomplete does not save change

### ISSUE THREAD

**Issue by Jal-Courtois** [sonata-project/SonataAdminBundle#2383]
Hey there. I have another issue when I use the sonata_type_model_autocompleted in a ssonata_type_collection. I can add an item and the autocomplete works well but when I tried to add a second item in my collection, the first is not saved.

Here is before adding the second item
![capture du 2014-09-01 11 36 07](https://cloud.githubusercontent.com/assets/8425920/4106602/e29f393a-31bb-11e4-9d44-bc608b1571c7.png)

When I add the second item
![capture du 2014-09-01 11 36 21](https://cloud.githubusercontent.com/assets/8425920/4106588/bb99c328-31bb-11e4-914e-7b912bf96cb5.png)

Finally after saving the change
![capture du 2014-09-01 11 36 41](https://cloud.githubusercontent.com/assets/8425920/4106595/ca7ecbfe-31bb-11e4-9551-46df50b809f0.png)

**Comment by laurencesmithever** [comment]
@pulzarraider @rande @EmmanuelVella 
Hi there,

Just wondered if you had any ETA on this fix?  We (http://www.everlution.com) have been using Sonata for a while now and love it, but this issue is causing us lots of problems.

If it's not something that you intend to fix soon, do you think you could point us in the right direction so that we can make a fix ourselves and submit a pull request?

Here is a screencast showing our issue, just for clarity: http://www.screencast.com/t/8l3rPmPpo6

Thanks,

Laurence

CC: @michcald

**Comment by laurencesmithever** [comment]
@pulzarraider @rande @EmmanuelVella - guys - sorry to pester but any help on this would be really appreciated.

**Comment by rande** [comment]
@laurencesmithever this is not due to Sonata. You need to check your javascript code. I have tested the code with the sandbox, and I cannot reproduce the issue.

**Comment by rande** [comment]
@Jal-Courtois I have also add a use case with the sandbox and I cannot reproduce. I guess the error is coming from your doctrine mapping configuration.

**Comment by auipga** [comment]
@laurencesmithever and others: above PR is a really dirty but working fix
