### ISSUE TITLE
Link option for search results

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#2581]
Actually search results have edit link: https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Block/block_search_result.html.twig#L33-L35

It could be interesting to have the possibility to choose between show and edit link with a configuration option, isn't it ?

Thanks.

**Comment by Soullivaneuh** [comment]
@rande Finally, I think we should implement a global "link mode" option for all admin link, including ORM.

I think about: 

* search results
* breadcrumbs link
* ORM relations

This option could be name `admin_default_link` with the following options:

* `edit` (as default for BC)
* `show`
* `show_edit` (`show` if available, otherwise try `edit`)
* `edit_show` (`edit` if available, otherwise try `show`)

Will try to work on it soon.

**Comment by webdevilopers** [comment]
:+1: 

Just what I was thinking about!

**Comment by rewotec** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
Trick you can do since #3772 with a custom abstract admin class:

```php
use Sonata\AdminBundle\Admin\AbstractAdmin;

class Admin extends AbstractAdmin
{
    protected $searchResultActions = ['show', 'edit'];
}
```

And make your admin classes extended this one. The show action will be choose by default.

But having a `getSearchResultActions` method on both `AbstractAdmin` and `AbstractAdminExtension` would be better.

In this case, we could create a extension returning a different value and get rid of inheritance.

@core23 What do you think?

cc @sonata-project/contributors

**Comment by core23** [comment]
Not quite sure, if we need this. We have `AbstractAdmin::getSearchResultLink` for this.

**Comment by Soullivaneuh** [comment]
> Not quite sure, if we need this. We have AbstractAdmin::getSearchResultLink for this.

This method is final.
