### ISSUE TITLE
sonata admin - data inconsistency

### ISSUE THREAD

**Issue by AlaaKanaan** [sonata-project/SonataAdminBundle#2655]
Hi guys!

if two users processing the same edit on the same entity at the same time, that caused one edit operation to override the other one....and many other undesired consequences occurs after that...by @zrashwani

**Comment by Uprzejmy** [comment]
Hi, i'm writing this to refresh the problem.
Probably you know that already, but there are two problems. Assuming we have two users, we can create model timeline for scenarios.

Ideal (for us) scenario is:
1. User1 gets object
2. User1 sends POST request with edited object
3. User2 gets object
4. User2 sends POST request with edited object

But different scenarios might occur:
First:
1. User1 gets object
2. User2 gets object
3. User2 sends POST request with edited object
4. User1 sends POST request with edited object

Second:
1. User1 gets object
2. User2 gets object
3. User1 sends POST request with edited object
4. User2 sends POST request with edited object

it's not hard to handle i think, because we can keep in session (or in another storage) date of GET request of object edit action, and compare with date of last object edition. This could be done easy by developers themselves. Problems are "best way of doing this" and scenarios for more than two ppl editing object.

Looking on this as the user of sonata-based application if i could get message that i need to look again on object, because sb has edited it. i would like to be able to compare those two states of object (sth like preview action).

**Comment by rande** [comment]
This issue is a classic problem of web application. There is no easy solution to solve this issue: server can be load balanced, user can open the edit form and never close the browser, etc ...

The doctrine optimist locking can be a solution but for now there is no integration. If you want to contribute:
 - you need to create a ``LockException`` at the ``SonataAdminBundle`` level
 - configure yours models to use the optimist locking (http://doctrine-orm.readthedocs.org/en/latest/reference/transactions-and-concurrency.html?highlight=optimistic#optimistic-locking)
 - Then implement the doctrine's exception at the ``SonataDoctrineORMAdminBundle``'s ModelManager
