### ISSUE TITLE
order by a not mapped column in list view

### ISSUE THREAD

**Issue by ghostika** [sonata-project/SonataAdminBundle#2724]
Hello,

I have a list view where I have start and end dates as columns, and I added a dynamic column, called status, what is not saved to the DB, but generated depending on the thing is started, ended, not started yet. I want to be able to sort the list by this value, but I realised, sorting can be done only on DB level. The good thing, that there is a DB representation of this sorting ( not started yet: order by startDate, ASC) ?

**Comment by eduardoconceicao** [comment]
+1

**Comment by greg0ire** [comment]
So you can change `createQuery` to take that into account right? What's the problem? Reopen if this is still relevant.

**Comment by eduardoconceicao** [comment]
@greg0ire The problem happens if you have non mapped column ins the list view and if you need to sort the list by the non mapped field. You cannot sort the column on the database because the column doesn't exist in the database level.

**Comment by greg0ire** [comment]
Yeah but you can still compute the status in the query and sort by that, right?

**Comment by eduardoconceicao** [comment]
No, there it could be some cases where you can but for the most of the non mapped fields you can't.

Imagine that you have an Entity

```php
class myEntity
{
    /**
    * @ORM\Column(type="string")
    */
    private $someField;

   public function getSomeNonMappedField()
   {
        $value = do some business logic that you can't do on a query

       return value;
   }
}
```

Then you have a list view from an admin that includes the someNonMappedField:

```php
class SomeAdmin extends Admin
{
    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('id')
           .....
            ->add('someNonMappedField', null, array(
                'label' => 'SomeNonMappedField'
            ))
}
```

How can you sort this? That's impossible with a query since the value is not queryable.

**Comment by greg0ire** [comment]
> do some business logic that you can't do on a query

Well yeah if you tell the problem like that there is literally no hope to solve that. And if you can't do it with SQL, I don't think it's reasonable to do it in php, right? You're not going to fetch all rows and sort them manually, are you?

**Comment by eduardoconceicao** [comment]
Well, imagine that sonata admin allows you to implement some manual sort on your records.

My first thought was to have a postLoadResults or something like that, that allows you to sort the results on PHP level. But then i realise that this solution only sorts the results of a page.

In this in mind, a possible solution (although not so efficient) could be have a way to register some custom sorting methods for a field (something like sortable callbacks).

```php
    /**
     * @param SortMapper $sortMapper
     */
    protected function configureCustomSortFields(SortMapper $sortMapper)
    {
        $sortMapper
            ->add('someNonMappedField', 'callback', array(
                'callback' => array($this, 'someNonMappedFieldSorter')
            ))
    }

    public function someNonMappedFieldSorter($valueA, $valueB)
    {
         return strcmp($valueA, $valueB);
    }
```

And having the power to register custom sorting filters the loading of objects from the database has to be conditional (since we need to load all the entries to sort them in PHP level).

```php
    if ($admin->hasCustomSortableFields()) {
         $entries = $this->getAllDatabaseEntries(); // probably get some partially objects or hydrate as array for performance reasons
    
        $entries = $this->applySorting($entries);
    } else {
        // proceed as usual
    }
```

I know that's not pretty but it will serve this purpose.

Without this feature and if you have a requirement like this you can't use sonata default list action so you'll have to implement it from scratch.

**Comment by greg0ire** [comment]
> But then i realise that this solution only sorts the results of a page.

Yeah, that's the core of the issue: imagine if the table has a billion rows. Fetching all the results, then sorting them in php will be incredibly inefficient. This must be done in SQL, your solution is not an option I'm afraid. Doing like this should be discouraged, so I'd say it's just fine the way it is.

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
> This must be done in SQL, your solution is not an option I'm afraid. Doing like this should be discouraged, so I'd say it's just fine the way it is.

Frankly, this is a shitty thing to be telling a client.

**Comment by greg0ire** [comment]
Well don't tell your client… just do it in SQL like you should.
