### ISSUE TITLE
Sonata\AdminBundle\Block\AdminListBlockService::validateBlock()

### ISSUE THREAD

**Issue by josephzhao** [sonata-project/SonataAdminBundle#2802]
Hello:

Compile Error: Declaration of Sonata\AdminBundle\Block\AdminListBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockServiceInterface::validateBlock(Sonata\AdminBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block)

should  use Sonata\CoreBundle\Validator\ErrorElement; 
or use Sonata\AdminBundle\Validator\ErrorElement; ?

Thanks

Joseph

**Comment by javiereguiluz** [comment]
@josephzhao here are some related issues that may help you solve his problem:

  * https://github.com/sonata-project/SonataAdminBundle/issues/2799
  * https://github.com/sonata-project/SonataAdminBundle/issues/2801

And here you can find more information about why this error is happening: https://gist.github.com/rande/9c0cfbd751d3e64b893f

**Comment by rande** [comment]
Thanks @javiereguiluz  ;)

**Comment by SiliconMind** [comment]
@rande Indeed this error is caused by incompatible bundle versions, but not users are to blame but the one who created wrong dependency in `composer.json` that allows any version of `BlockBundle` above `2.2.7` including latest incompatible ones.

I see that you fixed this with a4c4a00 but please note that `packagist` still [shows wrong dependency versions](https://packagist.org/packages/sonata-project/admin-bundle) for AdminBundle v 2.3.0 and 2.3.1.

I've just wasted over an hour to figure this out after my site crashed when I did `composer update` with `"sonata-project/admin-bundle": "2.3.0",` in my `composer.json` file. Can you please investigate this?
