### ISSUE TITLE
Consider using english sentence for translation key

### ISSUE THREAD

**Issue by lyrixx** [sonata-project/SonataAdminBundle#2910]
Right now, it's not possible to disable the translation in a SF2 application because the admin relies on the translation component. It's a nice feature. But I think it would be better to user "native english" for key. Like that, We could disable the translation and get anyway a nice admin and not an admin with key.

What do you think?

**Comment by pulzarraider** [comment]
Changing the translation keys from undescored strings to native english keys in all SonataAdmin (and related Sonata bundles) will be a BC break, because some projects may rely on these translation keys and may modify them in their application to their needs. 

This will be a lot of work and I am not sure about the benefits that it willl bring. Maybe it can be feature for some major version of SonataAdmin.

**Comment by rande** [comment]
@lyrixx the SonataAdminBundle used keys to translate the UI. So I guess the translator is mandatory.
