### ISSUE TITLE
Why is the sidemenu based on roles, while the rest isn't?

### ISSUE THREAD

**Issue by wouterj** [sonata-project/SonataAdminBundle#2930]
While writting the final chapter of the Getting Started docs, I was wondering why one would need to set-up Security and apply roles, just to display the sidebar. It seems very inconsistent, as the rest of the Sonata dashboard doesn't care about security at all by default (which is something that I really like btw).

I propose to either remove the requirement for the sidebar menu, or to add it to the complete page.

**Comment by core23** [comment]
Feel free to contribute and supply a PR.

**Comment by jordisala1991** [comment]
Not sure if this has changed a lot since 2015, but now, the list view, the form view, the show and the export view are based on roles. You cant export edit view, edit, remove if you dont have the required roles.

You can also add new roles, and the dashboard works with blocks that can be customizer with roles too.

Closing for now as I cant see the issue here. If you think this is still relevant, please ping me to reopen and discuss about this subject.
