### ISSUE TITLE
Incorrect exporter version in composer.json for Admin Bundle 2.1

### ISSUE THREAD

**Issue by rachel-walker** [sonata-project/SonataAdminBundle#3060]
In the composer.json file for Admin Bundle 2.1, you require sonata-project/exporter 1.*.  This is an incorrect version, as newer versions of sonata-project/explorer require versions of symfony 2.2+.  The version of sonata-project/explorer requirement should be changed to 1.2.3, which is the newest version designed for symfony 2.1.  With this incorrect requirement, when trying to use the AdminBundle's CRUDController's exportAction, you will get the error: PHP Fatal error: Class 'Symfony\Component\PropertyAccess\PropertyAccess' not found in [project folder]/vendor/sonata-project/exporter/lib/Exporter/Source/DoctrineORMQuerySourceIterator.php on line 61

**Comment by Soullivaneuh** [comment]
@rachel-walker I'm sorry but sonata-admin 2.1 is not maintained from a long time.

Please update to a newest version of sonata and ,BTW, a newest version of Symfony because these version is not maintained anymore.

If you still want to use this version, you should lock the good version of `sonata-project/explorer` on your own composer.json file.

I'm closing this issue because 2.1 would be edited anymore.

Regards.
