### ISSUE TITLE
Bug in listview on some entityAdmin with using nested associate

### ISSUE THREAD

**Issue by egordanilenko** [sonata-project/SonataAdminBundle#3114]
We are using nested associate like this:

``` php
<?php
...
class DeviceAdmin extends Admin
{
...
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('id')
            ...            
            ->add('deviceAccountLink.account') //FIXME: when deviceAccountLink is null sonata make new Account entity (with null id) -> throw exception  on SonataDoctrineORMAdminBundle:CRUD:list_orm_many_to_one.html.twig 
            ...
            ->add('_action', 'actions', array(
                'actions' => array(
                    'edit' => array(),
                    'delete' => array(),
                )
            ))
        ;
    }
...
}
?>
```

if deviceAccountLink (this is an entity) is not null and have account item - all right.
If deviceAccountLink is null - Sonata make new Account object and twig throw exception.

I'm find 2 ways to fix this trouble: 
- check value.id in twig template SonataDoctrineORMAdminBundle:CRUD:list_orm_many_to_one.html.twig 
- remove autocreate in method "getValueFromFieldDescription" in Sonata\AdminBundle\Twig\Extension\SonataAdminExtension

look both ways is not safe, what other options we can use?

**Comment by OskarStark** [comment]
can you please use

```
```php
<?php

your code...
```
```

**Comment by egordanilenko** [comment]
sorry, make it more readable

**Comment by jordisala1991** [comment]
You could use a custom getter method on your entity to check if the association exists and print the related method or print nothing otherwise.

IMO it works as expected, if you try to print a nested field and the the relation is null, it will fail.

Closing for now. If you think this is something we should fix in Sonata, please ping me to discuss it. If @sonata-project/contributors thinks the same, please reopen.
