### ISSUE TITLE
filter values are not translated

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataAdminBundle#3283]
<img width="962" alt="bildschirmfoto 2015-09-24 um 11 04 32" src="https://cloud.githubusercontent.com/assets/995707/10072357/3e6e73b6-62c1-11e5-93cb-48f6fcf0427d.png">

how should we solve this?
shall we introduce keys for this?
shall we bring this to a Sonata* translation domain scope?

**Comment by jvasseur** [comment]
The problem here is that they are translated twice : a first time by sonata when building the form and a second time by symfony when displaying it.

We could remove the translation on the sonata side and use the symfony one, or disable the translation on the symfony side. Both solution can be implemented using the ```choice_translation_domain``` option, but it requires symfony 2.7 to work.

**Comment by OskarStark** [comment]
:+1: for removing the translation in sonata and would like to use the translation method in the template directly

what do you think @rande @Soullivaneuh

**Comment by greg0ire** [comment]
It would be great to solve this because it can prevent people from asserting that their backend have zero missing translations in their admin.
