### ISSUE TITLE
Integration of SonataAdmin in own admin system

### ISSUE THREAD

**Issue by JHGitty** [sonata-project/SonataAdminBundle#3421]
I cannot find any documentation how to integrate SonataAdmin into an own admin system.

We don't want to use the "Full Stack" of SonataAdmin. We have own templates and own controllers.

**We just want to replace our CRUD to be handled with SonataAdmin**. We like to use our own controllers and templates without a lot of extra work.

Reason: We like the idea of "admin" classes. The filter system of SonataAdmin is great. It's great how SonataAdmin is working with relations between entities. But it would be a lot of work to convert our admin system and admin templates to SonataAdmin. That because it would be great to know how to integrate it easily in **our own controllers and templates**.

**Comment by pulzarraider** [comment]
SonataAdmin has it's own templates for filters, forms, datagrid and a lot of other features. We don't know how your own admin works, so such documentation will be too general. 

The easiest way how to start integrating SonataAdmin into your existing admin is overloading [standard_layout.html.twig](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/standard_layout.html.twig). You can overload blocks, that you don't need, create your custom menu, that will contain links to your old admin, that you want to keep.

Your overloaded CRUDControllers should extends the [Sonata's main CRUDController](https://github.com/sonata-project/SonataAdminBundle/blob/master/Controller/CRUDController.php).

In your Admin classes you will have to type `$baseRoutePattern` and `$baseRouteName` to be sure that no route will be in conflict with your old routes.

In many cases you will have to modify your own templates, because it contains logic that is tight coupled with the CRUDController or just use the default template.

Sonata is designed to be very flexible and a lot of parts of this project can be extended or overloaded, so feel free to ask more specific question that you will not find in the [documentation](https://sonata-project.org/bundles/admin/master/doc/index.html).

**Comment by greg0ire** [comment]
Well you could at least say thanks for the long answer @JHGitty . Closing.

**Comment by JHGitty** [comment]
Of course - thank you very much @pulzarraider ! :+1:
