### ISSUE TITLE
Filtering numbers instead of string property behaves different with sonata_type_model_autocomplete

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3424]
I have an `Employee` entity and a filter that searches all properties:

``` php
'property' => array('firstName', 'lastName', 'number)
```

Looking up an employee with __toString e.g. "Web Deviloper (1234)" works fine for 'Web' or 'Dev' but NOT for '123'. It works with the full number '1234' though.

Since the `number` column is an integer inside the database `sonata_type_model_autocomplete` does not query with `LIKE` like with `string`s but it uses the `=` operator.

I guess this is a good behaviour in general. But users will wonder why they get no result.
A workaround would be to add a custom `datagridFilter` for `number` with a callback.

Any opinions on this?
- https://github.com/sonata-project/SonataAdminBundle/issues/2360
- https://github.com/sonata-project/SonataAdminBundle/pull/2454
- https://github.com/sonata-project/SonataAdminBundle/issues/2529

**Comment by pulzarraider** [comment]
This behavior is caused by the number filter that is called in the dependent admin. The default type for [NumberFilter](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/NumberFilter.php) is [`NumberType::TYPE_EQUAL`](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/NumberFilter.php#L50), so `=` is used in the query. I am not sure if it's bug.

To fix the issue for your use case, you can try to change the filter type of `doctrine_orm_string` to

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.
I will try to comment on the issues anyway. I will close them if nobody else suggested a PR or similar.
