### ISSUE TITLE
sonata_type_datetime_picker wrong date persist to DB

### ISSUE THREAD

**Issue by ibasaw** [sonata-project/SonataAdminBundle#3518]
```php
->add('created', 'sonata_type_datetime_picker', [
    'format' => 'YYYY-MM-DD HH:MM:SS'
])
```

I type 30/12/2015 and got 30/01/2015 in DB

sf2.8.2

**Comment by core23** [comment]
Maybe this is related to your timezone? Can you check this behavior against the latest master branch.

**Comment by glukose** [comment]
Same issue here. The month property keeps going to 01, whatever you choose.

I've just tried with the lastest 3.x-dev (couldn't try the 4.x-dev because of some dependencies conflict with sonata-project/doctrine-orm-admin-bundle) but it didn't change anything.

`->add('dateDebut', 'sonata_type_datetime_picker', array(
                'required' => false,
                'label' => 'Date début',
                'format'=>'YYYY-MM-DD hh:mm:ss',
                'attr' => array(
                    'data-date-format' => 'YYYY-MM-DD hh:mm:ss',
                )
            ))`

In the form the submitted data looks like that : 
![selection_023](https://cloud.githubusercontent.com/assets/1611758/17659381/6627846c-62d2-11e6-9b2b-21b0729da61d.png)

Even though I changed the month.

**Comment by ibasaw** [comment]
i didn't use it in my project because of this

**Comment by BOB41K1987** [comment]
Any news about solving that problem?

**Comment by core23** [comment]
Looks like a config problem. The parameter 'MM' is used for minutes instead of 'mm'

**Comment by BOB41K1987** [comment]
Do you know what paremeter should I use for month? Or how can I fix that?

**Comment by rewrewby** [comment]
Working fine for me:
```php
->add('created', 'sonata_type_datetime_picker', [
    'format' => 'yyyy-MM-dd HH:mm:ss'
])
```
P.S. sonata-project/admin-bundle (v3.16.0)

**Comment by jordisala1991** [comment]
This looks more a problem with the format passed to the form type than an issue on sonata. Closing. If this is a bug ping me to reopen
