### ISSUE TITLE
Adding tabs without groups in Admin Forms

### ISSUE THREAD

**Issue by EricSivilog** [sonata-project/SonataAdminBundle#3524]
Hi there !

I am using Sonata Admin to develop the backend of my website, and came accross some strange behaviour yesterday. I am basically trying to have a form with two tabs, but do not need groups in each of these tabs. Hence I used in configureFormFields :

``` $formMapper
                ->tab('Infos')
                    ->add('name')
              ->end()
                ->tab('Jaquettes')
                ->end()
                ;
```

When doing so, I get an error that says: You should close previous tab "Infos" with end() before adding new tab "Jaquettes". If I enclose the "->add('name')" within a with/end statement (i.e. a group), everything works as expected. Curiously, if I keep the scheme above but add another "->end()" after the first one, things work fine too.

This is using Admin Bundle  version "dev-master 2e68c08". Is that the expected behaviour, i.e. do we have to use groups when using tabs? Thanks a lot ! :-)

**Comment by debach** [comment]
I came accross the same issue and 

    ->tab('Infos')
        ->add('name')
    ->end()
    ->end() // what the heck?
    ->tab('Jaquettes')
    ->end();

works as you have said.

Basically, what happens is this:

* [Calling `add()` invokes `addFieldToCurrentGroup`.](https://github.com/sonata-project/SonataAdminBundle/blob/master/Form/FormMapper.php#L90)
* [Calling `addFieldToCurrentGroup` calls `getCurrentGroupName`.](https://github.com/sonata-project/SonataAdminBundle/blob/master/Mapper/BaseGroupedMapper.php#L268)
* `getCurrentGroupName` has side effects, because it [automatically creates a new group](https://github.com/sonata-project/SonataAdminBundle/blob/master/Mapper/BaseGroupedMapper.php#L288) if there is none open.

Of course, this behavior doesn’t go well with the fake indentation-style syntax and also isn’t documented anywhere.

**Comment by Gradius30** [comment]
Hello guys. Has anybody solved this issue so far or do we always have to use another `->end()` at `->tab()` end?

**Comment by lainosantos** [comment]
Hello. There is a fix to this?

**Comment by arirangz** [comment]
Hello,

The issue is still there.

Thanks

**Comment by wbloszyk** [comment]
It is not bug but this things can be improve.
`add()` methods calls `addFieldToCurrentGroup($fieldName)` which call `protected function getCurrentGroupName()`:
```php
protected function getCurrentGroupName()
    {
        if (!$this->currentGroup) {
            $this->with($this->admin->getLabel(), ['auto_created' => true]);
        }

        return $this->currentGroup;
    }
```

It's mean:
```
->tab('Infos')
    ->add('name') //it is equal to ->with($this->admin->getLabel(), ['auto_created' => true])->add('name')
->end() // this end is for with() called by add('name')
->end() // this end is for tab() 
->tab('Jaquettes')
->end()
;
```

**Comment by arirangz** [comment]
Thanks for the explanation, that's very clear.
Maybe it shouldn't add the admin label by default if there is a tab.

**Comment by VincentLanglet** [comment]
I think that the `auto_created` should not count when calling the method `end()`.

```
->tab('Infos')
    ->add('name') //it is equal to ->with($this->admin->getLabel(), ['auto_created' => true])->add('name')
->end() // this end is for with() called by add('name') but since it's auto_created, it close the tab too.
->tab('Jaquettes')
->end()
;
```
