### ISSUE TITLE
how to put sonata nav to the top?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataAdminBundle#3536]
is there a setting?

**Comment by rande** [comment]
Nop, you cannot do than, unless you rewrite template and css.

**Comment by OskarStark** [comment]
ok, are you interested in a config way, so i can create PR, because we need this for one of our customer

**Comment by rande** [comment]
Does the theme support this feature ? Also, it will be great to check if nothing break also it will be harder to maintain 2 layouts, so maybe just a cookbook might be a good solution.

**Comment by javiereguiluz** [comment]
@rande AdminLTE2 template supports the top navigation via the `layout-top-nav` option (see https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#layout).

**Comment by OskarStark** [comment]
yes the theme supports it like javier said, but i'm not sure if this is simple, we have to check that

or did you used it in this way @javiereguiluz ?

**Comment by OskarStark** [comment]
btw. are we using the version 2 of the theme?

**Comment by javiereguiluz** [comment]
@OskarStark these days I'm battling to integrate the AdminLTE2 in a bundle ([details](https://github.com/javiereguiluz/EasyAdminBundle/pull/791)), so I'm not an expert in this template. However, as you can see in https://almsaeedstudio.com/themes/AdminLTE/pages/layout/top-nav.html  the "top nav layout" is as easy as adding `.layout-top-nav` class in the `<body>` and putting the menu contents in the `<header>` instead of the `<aside class="main-sidebar">` element.
