### ISSUE TITLE
Filter in sonata_type_model or other Selects

### ISSUE THREAD

**Issue by alleswasrechtist** [sonata-project/SonataAdminBundle#3639]
Hey,

I startet using this Bundle and really like it so far. I wonder if it is possible somehow to show Filter-Options in normal Selectboxes (Select2), especially when using sonata_type_model as form element. I know that there is a sonata_type_model_autocomplete, but I think my list is too small for this and I want to show the values right from the beginning (without having to enter 3 chars).

Is there any easy way to achieve this?

Thank you in advance
Philipp

**Comment by greg0ire** [comment]
I think doing that is as simple as that : `$datagridMapper->add('your_linked_entity')`. Works for me, at least.

**Comment by alleswasrechtist** [comment]
Ah that was too easy - in my testing env there were just too few objects. As soon as the list gets longer, the field for filtering appears! Thank you!

It really seems like doc would need some updates. Is it possible to contribute?

**Comment by greg0ire** [comment]
I was just going to ask you :)

I looked at [the current doc](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/doc/getting_started/the_list_view.rst), and there are several things you could fix : 

1. Add a simple example like yours
2. Regarding the "Filtering by Category" § I think simply doing `add('category.name')` would work just as well, wouldn't it @WouterJ ?
3. Maybe you did not find anything because you looked at the 2.3 docs ? Backporting some of the master doc to 2.3 would help .

Some fixes are more demanding than others feel free to pick and choose what you want.

**Comment by greg0ire** [comment]
I see this would be your first contribution on github, so if you need more details, read [the specific §](https://github.com/sonata-project/SonataAdminBundle/blob/master/CONTRIBUTING.md#contributing-to-the-documentation), and do not hesitate to ask for help if you need more details.

**Comment by greg0ire** [comment]
ping @WouterJ @alleswasrechtist

**Comment by greg0ire** [comment]
@alleswasrechtist , please respond
