### ISSUE TITLE
Sorting sonata_type_model choices

### ISSUE THREAD

**Issue by philippsahrmann** [sonata-project/SonataAdminBundle#3640]
Hello,

one more question: Is there an easy way to sort the choices offered by the sonata_type_model form field? Unfortunately, it seems like the field is only sorted by id. Of course, I could create a custom query and provide it, but this would be quite awful since I want to set the sort order on every x to One Relationship that I use. It would even be okay to sort the resulting array of choices, but I have not figured out how to do this.

Thank you!

Philipp

**Comment by greg0ire** [comment]
I think [using the OrderBy doctrine mapping](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/tutorials/ordered-associations.html) on your entity should do the trick (provided you are using the ORM).

**Comment by alleswasrechtist** [comment]
Unfortunately, this only seems to work for a To-Many Relation. I have a Customer who can have a certain Contract. Now I want to show all Contracts in alphabetical order (form field type for selecting the Contract is sonata_type_model).

(actually, I want to sort by Contract->Provider->name Contract->name)

**Comment by greg0ire** [comment]
> (actually, I want to sort by Contract->Provider->name Contract->name)

Please fix this sentence

**Comment by greg0ire** [comment]
If you one a One-To-One association, there is nothing to order, your list will always have one element, won't it?

**Comment by alleswasrechtist** [comment]
Oh sorry for that. Each Contract is connected to a Provider (Many To One). In the Customer-Admin, the contracts in the dropdown selection are shown by the name of their Provider and their name. E.g.:

Vodafo Superflat
T-Mibole Magenta
Vodafo XY

Now in my Customer admin, I can choose one contract for a customer. I have a sonata_type_model field, in which all Contracts are shown in the way explained above. The Problem is that they are not sorted in the sonata_type_model dropdown.

Thanks for your help!

**Comment by greg0ire** [comment]
I think you might indeed have to use custom code for this one.

>  but this would be quite awful since I want to set the sort order on every x to One Relationship that I use

Unless all your relationships displayed in filters are indirect, you won't have to.

**Comment by alleswasrechtist** [comment]
> Unless all your relationships displayed in filters are indirect, you won't have to.

So if I only wanted to sort by the Contracts name, what would be the easy solution for this?

**Comment by greg0ire** [comment]
My bad, after a quick look, it seems you would have to do something like this : 

`->add('offer', null, [], null, ['query_builder' => 'your query builder')`. I see no sort option in Symfony itself.

**Comment by greg0ire** [comment]
BTW, I'm not sure this really is a Sonata issue, in fact. How would you do that with the `entity` form type in Symfony?

**Comment by greg0ire** [comment]
ping @alleswasrechtist

**Comment by alleswasrechtist** [comment]
Hi greg0ire, sorry for my late reply, I was on holiday for the last weeks. You are right, it seems to be rather a Symfony-related topic. When I have time to work on the project during the next days, I will try to find a solution since defining the order of the Entity selection seems to be a common problem for me.

Thanks for your help, I will keep you updated!

**Comment by greg0ire** [comment]
Sooo… ?

**Comment by jordisala1991** [comment]
Old issue, related more with Symfony than with this bundle, without response. Closing
