### ISSUE TITLE
Filter by Translated values of the Entity 

### ISSUE THREAD

**Issue by redjanym** [sonata-project/SonataAdminBundle#3677]
Hello, i am using SonataTranslationBundle and right now im having this problem when it comes to filtering the values of an entity. 
For example, i have an Entity with a field NAME which is translated in English and Italian. I am in Italian language and in the listAction i get to see the translated value in Italian but when i filter by the NAME field, the query takes in consideration the value in the default language, which is English. Like this, i have:
Name                   |  name_it
Web developing   |  Sviluppo Web
If a search for Name = "Sviluppo Web" it returns zero rows, if i search for "Web Developing" it returns to me "Sviluppo Web". 
How can i search in the value according to the _locale of the Request object and if does not exists return the value in the default _locale? 

Thanks in advance.

**Comment by jordisala1991** [comment]
This is probably related to this PR: https://github.com/sonata-project/SonataTranslationBundle/pull/143

It was merged on december 2016, while this issue is from march 2016.

Closing since there is no more information and probably fixed on latest releases.

If you still having this issue, please ping me to reopen or probably it would be better to publish an issue on the SonataTranslationBundle
