### ISSUE TITLE
Unable to find template "@Admin/CRUD/base_show_macro.html.twig"

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/SonataAdminBundle#3684]
```
Unable to find template "@Admin/CRUD/base_show_macro.html.twig" in SonataAdminBundle:CRUD:base_show.html.twig at line 14.
```
With symfony/symfony ^2.8
Seems to have been introduced in [95d9d6c](https://github.com/sonata-project/SonataAdminBundle/commit/95d9d6cbd6d981ef53af55561ad7be9f455274ad) by #3657

**Comment by ju1ius** [comment]
`"@Admin/CRUD/base_show_macro.html.twig"` This looks weird... Is this a new notation or sthg ?

**Comment by greg0ire** [comment]
Ping @sidz @Saint-Cyr . It does look weird

**Comment by greg0ire** [comment]
Having tests would be great

**Comment by greg0ire** [comment]
Thanks for fixing this @core23

**Comment by sidz** [comment]
@greg0ire @ju1ius @core23, Yep, there is a bug, but only with vendor name **Admin** (this is my bundle name where I made this feature) instead of **SonataAdmin** for SonataAdmin project (it's just copy-paste).

But @SonataAdmin/CRUD/base_show_macro.html.twig notation better (it's faster) then SonataAdminBundle:CRUD:base_show_macro.html.twig.

You can look into TwigBundle source: https://github.com/symfony/twig-bundle/blob/master/Loader/FilesystemLoader.php 66 line **findTemplate** method.
Where you can find try-catch. Symfony will tryi to get template with @SonataAdmin/CRUD/what_ever.html.twig. If there is no required template, twig throw exception (https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Loader/Filesystem.php line 168) which will be catched in the FileSystemLoaded.php and will try to find in the catch.

This means, if you are using SonataAdmin:CRUD:what_ever.html.twig you always will have exception in the try.

Of cource this is actual only for the first run, because all of this templates will be cached.

**Comment by greg0ire** [comment]
:-1: , the best practices docs does not even talk about the `@` notation : http://symfony.com/doc/current/best_practices/templates.html#template-locations

**Comment by greg0ire** [comment]
Or in the docs http://symfony.com/doc/current/book/templating.html#referencing-templates-in-a-bundle

**Comment by ju1ius** [comment]
@greg0ire It is documented here: [namespaced twig paths](http://symfony.com/doc/master/cookbook/templating/namespaced_paths.html)

@sidz However when contributing to a project, one should try to respect the code standards in use. And Sonata uses the standard notation.

**Comment by greg0ire** [comment]
Could catch @ju1ius . It is strange that there isn't even a reference to it in the docs I mentioned.
