### ISSUE TITLE
3.0.0 is not released yet and team is planning 3.1.0? What did I miss?

### ISSUE THREAD

**Issue by reypm** [sonata-project/SonataAdminBundle#3837]
@OskarStark @Soullivaneuh @core23 @greg0ire Hi there guys, at this point I am very confused :( I have been waiting for a stable release to be used on top of Symfony 2.8/3.0 and I think that is what the team has been working on - maybe I am wrong - such version I though was 3.0.0 but surprise I can see a 3.1 branch and some PR talking about a near release. So after read this:

- https://github.com/sonata-project/SonataAdminBundle/issues/3731 (apparently 13 of 30 issues closed)
- https://github.com/sonata-project/SonataAdminBundle/issues/3545
- https://github.com/sonata-project/SonataAdminBundle/issues/3468
- https://github.com/sonata-project/SonataAdminBundle/issues/3467

I am still **more** confused so I should ask: what is the "stable" version at this moment? if I have not started the project just yet waiting for "stable" release, what I should do? Keep waiting? Use "dev" branch?

I need some guidance on this. Advice? Toughs? 

PS: If the post of my authority (the three latest) aren't helpful at this point I will close them or any of you do it

**Comment by Soullivaneuh** [comment]
> 3.0.0 is not released yet

Wrong: https://packagist.org/packages/sonata-project/admin-bundle#3.0.0

Issue #3731 (3.0.0 release todo) is more a todo list to make all bundle compatible with the new sonata version management: #3053.

The issue is not closed yet because admin-bundle 3.0 is released but not all the sonata bundle are compatible with it for now.

For #3545, the google doc is not relevant anymore. In a nutshell, 3.0 is the old 2.4-dev. Be decide to bump a new major to mark a new start of management.

> I can see a 3.1 branch and some PR talking about a near release.

There is no 3.1 branch, only 3.x. Please re-read #3053.

**Comment by greg0ire** [comment]
You seem to be confused by the fact that admin 3.1.0 is out, and there is not a 3.0 for every bundle yet. Keep in mind that starting now, releases will not be synchronized anymore, and semver will be followed instead, which means you could end up with sonata admin 7 and sonata user 4. But don't worry, Composer will tell you if they are not compatible. Having desynchronized releases is a very good thing, it means we can release more often, independently from other bundles (or Symfony, for that matter), but the best news is that since we follow semver, you will now if there are BC-breaks or not, and how to upgrade.
So while the 2.3 => 3.0 migration might be painful, it will be the last painful migration.

**Comment by Koc** [comment]
Where can I find any announcement about 3.0 releasing and new features?

**Comment by Koc** [comment]
https://sonata-project.org/blog/archive no any note in the blog about release. So silent ;)

**Comment by greg0ire** [comment]
I think we're waiting for all bundles to be released before making any noise.

**Comment by reypm** [comment]
@Soullivaneuh no, no problem, get it now thx @greg0ire so if I get it right we can't use this 3.0 just yet because all the bundles aren't compatible? right?

**Comment by greg0ire** [comment]
Well it depends on what sonata bundles you are using. If all the bundles you are using have are checked in #3731 , you can migrate.

**Comment by clytemnestra** [comment]
Will the 3.0 sonata bundles be compatible with Symfony 2.8?

**Comment by Soullivaneuh** [comment]
> Will the 3.0 sonata bundles be compatible with Symfony 2.8?

Depends on which bundles. The goal is to start the new release management ASAP.

About admin, core and doctrine-orm, I'm using them from a while with SF 2.8, works great.

**Comment by Soullivaneuh** [comment]
Can we close the issue @reypm?

**Comment by clytemnestra** [comment]
Would be great if MediaBundle can be updated, too.

**Comment by Soullivaneuh** [comment]
@clytemnestra It's planned: https://github.com/sonata-project/SonataAdminBundle/issues/3731

Please stay focus on the issue subject.

**Comment by reypm** [comment]
@Soullivaneuh yes, closed!
