### ISSUE TITLE
Unable to find template

### ISSUE THREAD

**Issue by arlyxiao** [sonata-project/SonataAdminBundle#399]
Unable to find template "SonataUserBundle:Admin:Core/user_block.html.twig" in "SonataAdminBundle::standard_layout.html.twig" at line 101. 

The configuration
[symfony]
    git=http://github.com/symfony/symfony.git
    version=v2.0.5

**Comment by firestorm23** [comment]
I found that if you use default SonataUserBundle which is extends FOSUserBundle, while overriding templates, you need to point to FOSUser path rather than SonataUser
In my case, that bug was fixed when I changed 
`templates:
        user_block:           'SonataUserBundle:Admin:Core:user_block.html.twig'`
 to 
`templates:
        user_block:           'FOSUserBundle:Admin:Core:user_block.html.twig'`

That setting lead to loading template
`vendor/sonata-project/user-bundle/Resources/views/Admin/Core/user_block.html.twig`
despite of pointing to FOSUserBundle path in config.yml
