### ISSUE TITLE
Terrible Documentation

### ISSUE THREAD

**Issue by Mentos93** [sonata-project/SonataAdminBundle#3995]
I don't understand how the 'documentation' on the official website can be called documentation, because that documentation is utterly poor, and really incomplete. 

If you want feedback, then you'll get feedback. It is terrible! Documentation should be written in such a way that almost any possible noob should almost immediately understand what is discussed and how to work with it. But here you get some random code snippets with some small paragraph that's suppose to be an explanation, and then sometimes it end with a silly comment 'no get back no work!' How stupid! 

Every time I have a problem, I know I can't look at the documentation because I know nothing is explained there, and then I ask on StackOverflow. Then I get answers there to look at the documentation!

Aarrrghhhh!!! Please fix it!

**Comment by core23** [comment]
If you like to pay us for that, we can do it!

We are s small team and we are all humans with a normal life and a regular job. This is a free open source projects which is based on contributions from other developers. Feel free to contribute!

**Comment by Mentos93** [comment]
Ok, snap. I'm sorry. My bad. Can I remove this issue?

**Comment by Soullivaneuh** [comment]
The documentation was already refactored quite time ago AFAIK. If people on SO just give you links instead of answer me, I don't see how we can resolve this.

> I would like to contribute, but how am I suppose to do that if i can't understand it without propper documentation?

You can start by not open issues containing "your documentation is terrible" and "Aarrrghhhh!!! Please fix it!".

Follow docs, test, see if it does not work and open an issue following the bug report template if you **really think** you find a bug of something false on the documentation.

Also read or re-read: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md
