### ISSUE TITLE
passing ajax parameter to createAction

### ISSUE THREAD

**Issue by Pablossoo** [sonata-project/SonataAdminBundle#4129]
```
$(document).on('click','.fc-day',function () {
             var date=$(this).attr('data-date');
             console.log(date);
                 $.post("{{ path("admin_fitness_event_create") }}",{'date':date}, function (data) {
                     $("#myModal").modal('show').find('.modal-body').html(data)
                 })
             });
```
I would like sent value variable date to database via ajax, how I can do this? I tried through prePersist method, but she doesn't recognize ajax request

 ```
public function prePersist($object)
{

    $date=$_GET['date']; // not isset
        $object->setStart($date);
        $object->setEnd($date);

}
```

**Comment by greg0ire** [comment]
Hi, we try to keep Github issues for bug reports and feature requests only. If you have a question, please ask it on Stack Overflow.

**Comment by Pablossoo** [comment]
I asked and nobody wants to help

**Comment by greg0ire** [comment]
You can link to the SO question here if you want to.

**Comment by Pablossoo** [comment]
http://stackoverflow.com/questions/39358366/sonata-get-ajax-request-prepersist

**Comment by Pablossoo** [comment]
Can you help me? i need simple example...

**Comment by greg0ire** [comment]
If you're trying to use `$_GET` directly, I'd say learn Symfony first, this is not how things are supposed to be done. Also, if I were you, I'd talk a bit more about the context b/c who knows if AJAX is even the right solution to your problem. Plus your code raises so many questions, I mean why would you use a data attribute instead of a regular form to create your event?
