### ISSUE TITLE
Is it have sense to avoid PHPUnit warnings?

### ISSUE THREAD

**Issue by osavchenko** [sonata-project/SonataAdminBundle#4286]
So will be it useful? And if yes what base branch should be used for it? I can help you with it.

**Comment by greg0ire** [comment]
I think it was decided against doing that because we can't use `createMock` with phpunit 4, which is in use for old versions of php, and as for using `getMockBuilder()->getMock()` everywhere, I don't recall the reason ( @sonata-project/contributors , do you ?).

This warning make the output quite annoying to work with, so I'd be in favor of such a fix though. If you want to do it, you should do it on the stable branch (3.x).

**Comment by core23** [comment]
Maybe we can create wrappers for internal test? 

https://github.com/sonata-project/SonataBlockBundle/pull/357

**Comment by osavchenko** [comment]
PHPunit 4 support will be thrown on February 3, 2017. So, I think we can move forward and ignore that version.
I'll take this issue and will work on it.

**Comment by greg0ire** [comment]
PHPunit5 is not compatible with php 5.6, that's why we have this problem.

**Comment by osavchenko** [comment]
Do you mean `< 5.6`? Because in PHPUnit 5.7 I saw
```"php": "^5.6 || ^7.0",```

You think that upgrading php from 5.3 to 5.6 is not good idea?

**Comment by greg0ire** [comment]
Yes forgot the <

**Comment by greg0ire** [comment]
Upgrading is a good idea, and is already done on master, but we won't do it on 3.x

**Comment by osavchenko** [comment]
So, fixing phpunit warnings better to do on master?

**Comment by greg0ire** [comment]
It would be better to do what @core23 suggested so that both branches don't diverge too much IMO. Plus there are far more builds on 3.x, so the problem is more important here.
