### ISSUE TITLE
ModelChoiceList : SimpleChoiceList class has been removed in favor of ArrayChoiceList.

### ISSUE THREAD

**Issue by pbeliberty** [sonata-project/SonataAdminBundle#4484]
### Environment
Symfony >= 3.0.0
Sonata Admin 3.*

#### Sonata packages
Sonata Admin 3.*

## Subject

The Symfony\Component\Form\Extension\Core\ChoiceList\SimpleChoiceList class has been removed in favor of Symfony\Component\Form\ChoiceList\ArrayChoiceList. [[source upgrade to v3 symfony](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md)]

But the ModelChoiceList still has a[ reference on it](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/ChoiceList/ModelChoiceList.php#L18). 

(sorry, I don't have all the info about my config or how to reproduce but all the main info are here I think  )

**Comment by jlamur** [comment]
https://github.com/sonata-project/SonataAdminBundle/issues/4499

**Comment by jlamur** [comment]
Maybe a deprecation should be added to the `ModelChoiceList` class, and the class should be removed when Sonata will support Symfony >= 2.7.

**Comment by OskarStark** [comment]
can you provide a PR @jlamur ?

**Comment by jlamur** [comment]
@OskarStark Yes sure. Could you just help me writing the deprecation message text? I don't know if I should mention a specific version of Sonata (for example, the version when Symfony <2.7 will no longer be supported, if this is planned) or anything else...

Just to be clear: The `SimpleChoiceList` class was removed in Symfony `3.0`, and is deprecated since `2.7`. The replacement class (`ArrayChoiceList`) exists since `2.7`.
