### ISSUE TITLE
Sonata_type_collection with abstract Entity and inherited children

### ISSUE THREAD

**Issue by Tofandel** [sonata-project/SonataAdminBundle#4519]
If you define an abstract entity with some inherited children to it :

```php
/**
 * @InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"circle" = "Circle", "square" = "Square"})
**/
abstract class shape {
    protected $id;
    protected $options;
}
/**
 * @Entity
**/
class square extends shape {
}
/**
 * @Entity
**/
class circle extends shape {
}
```

And you have an AdminClass like this :

```php
//Children refering to an ArrayCollection of class shape
 $formMapper->add( 'children', 'sonata_type_collection', array(
					 'by_reference' => false,
					 'label'        => 'children_inputs'
				 ), array(
					 'edit'     => 'inline',
					 'inline'   => 'table',
					 'sortable' => 'position',
					 'multiple' => true
				) );

```
The problem comes with the add button for the inlined collection, while in other forms like edit => modal or a direct admin form to the shape class, you have multiple add buttons for each child class : 
 - add square
 - add circle
 - ...

When in edit => inline there is only the add button, which will obviously throw an error because it will try to instanciate an abstract class.

Any thoughts or fix for this, or maybe an option that I'm just missing ?

**Comment by ioweb-gr** [comment]
I'm having the same behavior as well with a `One-To-Many` association when using inline edit. 

@Tofandel  if you manually add one item to the collection. Do you get the same error then? I've noticed that it would show me two `add new` buttons and the form displayed if I manually created an item in the DB on the 'Many' side and associated it with my `One` side

In addition modal way will also fail for me unlike @Tofandel mentions because of `NotNullConstraintViolationException` .

My goal is to be able to allow users to add a DiscountRule with multiple RuleConditions in one go from DiscountRuleAdmin but I don't want to leave RuleConditions hanging in the db that are not associated to any DiscountRule. 

However If I remove the `nullable=false` restriction and sacrifice data integrity I just get a RuleCondition created without being associated to the DiscountRule. The adders from DiscountRule are never called (couldn't make the debugger break execution inside them). 

In the RuleConditionAdmin I'm unable to get a reference to the "parent" DiscountRuleAdmin and it's subject to update the RuleCondition manually on prePersist or preUpdate. It seems that the abstract class' admin is completely isolated even though it's invoked via another Admin class and it persists the object immediately as if the user just tried to add a RuleCondition directly and not as part of the DiscountRule. 

My abstract class 
```php 

/**
 * RuleCondition
 *
 * @ORM\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"rc_user" = "RuleConditionUser", "rc_room_type" = "RuleConditionRoomType"})
 */

 abstract class RuleCondition implements RuleConditionInterface
{
     /**
      * @var $rule DiscountRule
      *
      * @ORM\ManyToOne(targetEntity="AppBundle\Entity\DiscountRule", inversedBy="conditions")
      * @ORM\JoinColumn(nullable=false)
      */
    protected $rule;
```

```php

class DiscountRule
{

    /**
     * @var $conditions
     * One DiscountRule has Many Conditions.
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\RuleCondition",mappedBy="rule", cascade={"persist"})
     */
    protected $conditions;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->conditions = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add condition
     *
     * @param \AppBundle\Entity\RuleCondition $condition
     *
     * @return DiscountRule
     */
    public function addCondition(\AppBundle\Entity\RuleCondition $condition)
    {
        $condition->setRule($this);
        $this->conditions[] = $condition;

        return $this;
    }

    /**
     * Remove condition
     *
     * @param \AppBundle\Entity\RuleCondition $condition
     */
    public function removeCondition(\AppBundle\Entity\RuleCondition $condition)
    {
        $this->conditions->removeElement($condition);
    }

    /**
     * Get conditions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getConditions()
    {
        return $this->conditions;
    }
```

I'd appreciate any suggestions to where I should look.

**Comment by ioweb-gr** [comment]
In case anyone else is facing the same issue and comes here, I ended up using InfiniteFormBundle's PolyCollection for this use case until this bug is fixed because nothing else I tried worked.

**Comment by ja1cap** [comment]
+1 faced with the same problem

**Comment by Quberik** [comment]
same problem here

**Comment by victorvassilev** [comment]
Anyone with a solution that will allow us to effectively use the sonata_media field?

**Comment by Quberik** [comment]
we hope someone will solve the issue soon

**Comment by kunicmarko20** [comment]
@victorvassilev @Quberik @ja1cap if you have time and idea, try to provide a PR to fix this.

**Comment by skydiablo** [comment]
+1

**Comment by core23** [comment]
> +1

-23 * 42 / 17

Adding something useful or working on this topic will help even more @skydiablo

**Comment by tonyellow** [comment]
I am also facing this problem.

**Comment by Moelanz** [comment]
What is the status on this?

**Comment by lucchese-pd** [comment]
What is the status on this?
