### ISSUE TITLE
BC Break #4405 - FormMapper doubles '__'

### ISSUE THREAD

**Issue by jlamur** [sonata-project/SonataAdminBundle#4549]
As mentionned in my comment here https://github.com/sonata-project/SonataAdminBundle/pull/4405/files#r126384740, field names containing **__** (two underscores) now get transformed to **____** (four underscores). This was not the case before this pull request and must be fixed.

**Comment by jordisala1991** [comment]
This might be improved by refactoring a lot the code or using another character, but since this is in the codebase for a lot of time now, I dont think we could consider it BC break now.

If any of the @sonata-project/contributors dont agree with this, please reopen, Im closing for now. We might get in the future someone who wants to improve this part.
