### ISSUE TITLE
Improve FieldDescription options.

### ISSUE THREAD

**Issue by jlamur** [sonata-project/SonataAdminBundle#4558]
## Subject
At the moment, `FieldDescription` options are used on-the-fly by templates.
It could be great to have an `OptionsResolver` to parse these options.

### Benefits
All the benefits of using an `OptionsResolver` ([list options](https://stackoverflow.com/questions/40421034/how-do-i-know-what-options-are-available-as-3rd-argument-of-listmapper-add-in/40566437), require them, default values, validation rules, etc...).
We could even imagine to generate documentation pages with the help of the `OptionsResolver`.

### Implementation / BC
Because users / bundles may use some options not defined by sonata, we must provide a way to extends / add options to the `FieldDescription` of any type.
Moreover, make it BC would be as simple as catching [UndefinedOptionsException](http://api.symfony.com/3.3/Symfony/Component/OptionsResolver/Exception/UndefinedOptionsException.html) and throwing a deprecation instead.

WDYT?

**Comment by greg0ire** [comment]
I think it's a great idea, not sure why it wasn't done like that in the first place. Maybe the options resolver wasn't that well known at the time?

**Comment by VincentLanglet** [comment]
There was some discussions about this: 
- https://github.com/sonata-project/SonataAdminBundle/pull/7103
- https://github.com/sonata-project/SonataAdminBundle/pull/7101
- https://github.com/sonata-project/SonataAdminBundle/pull/7099

Some options are global: `type`, `template`, `role`, ...
Some options are specific: `inverse` for boolean type, `currency`, `route` for url type, ...
Custom option could be possible for custom FieldDescription. I could indeed create a type `Amount` with an option `show_currency: bool` to display or not the currency.

So I'm not sure we can use an option resolver, since we should allow every possible options.
Or we have to say that non-generic options should be in a key `templateOptions` and this require a lot of BC-break.
Plus it's just moving the issue from `options` to `templateOptions`...
