### ISSUE TITLE
The build is broken

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataAdminBundle#4685]
https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/284104804

**Comment by greg0ire** [comment]
There has been a recent release of Symfony: https://github.com/symfony/symfony/releases/tag/v3.3.10

**Comment by greg0ire** [comment]
Here is the changelog: http://symfony.com/blog/symfony-3-3-10-released

**Comment by jlamur** [comment]
Maybe we need to mock `render` instead of `renderResponse` here: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Tests/Controller/CRUDControllerTest.php#L147

This change was introduced in SF here: https://github.com/symfony/symfony/pull/24431/files#diff-064e58dbe11951327d614e6922caaae5L234
And their tests were fixed the same way here: https://github.com/symfony/symfony/pull/24431/files#diff-ec4253bae85e4333ebb8d6478f7447ecL454

**Comment by jlamur** [comment]
Tested. It works. I'll provide a PR.
