### ISSUE TITLE
Custom changes in Sonata Admin PreUpdate prevent persiting of object

### ISSUE THREAD

**Issue by jackd248** [sonata-project/SonataAdminBundle#4979]
I am using Doctrine 2.4.8 in my Symfony 2.8.34 project.

My Problem is that custom changes I made in the `preUpdate` function preventing the expected changes from the admin form. Dependent on a choice field a new event should been created or deleted.
```
class CustomAdmin extends AbstractAdmin {

   public function preUpdate($object) {
      ...
      if ($object->isDetached()) {
         $event = new Event();
         ...
         $object->setDetachedEvent($event);
      } else {
         $object->setDetachedEvent(null);
      }
   }
}
```

Now, the line `$object->setDetachedEvent(null);` turns everything crazy. The first time I'm saving the form my custom changes in that `preUpdate` function are executed, but the changes in the fields of the admin form are ignored. The second time the changes from the admin form were executed. If I remove the line above, everythings works fine.

So, anybody has an idea how to handle this problem?

**Comment by jordisala1991** [comment]
Did you solve your issue? to me looks more related to your entity code and your mapping annotations and less related to how Sonata handles preUpdate.

Closing for now, since preUpdate should work just fine. If you can provide more information like an stack trace and a correct usage of the issue template then I will reopen.
