### ISSUE TITLE
Controllers Should Not Be Referenced With Single Colon Syntax

### ISSUE THREAD

**Issue by Selion05** [sonata-project/SonataAdminBundle#5251]
## Feature Request

related to #5227 using `'::'` removes the deprecation notices
[link](https://github.com/sonata-project/SonataAdminBundle/blob/312593909ca0b21cf723e07660b966a15a385916/src/Route/RouteCollection.php#L86)

**Comment by valkars** [comment]
And also https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/config/routing/sonata_admin.xml#L4
Referencing controllers with FrameworkBundle:Redirect:redirect is deprecated since Symfony 4.1, use "Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction" instead.

**Comment by Selion05** [comment]
what about https://github.com/sonata-project/SonataAdminBundle/blob/57a4e6d4556dc4ac476b9658df66cb5e11174156/src/Route/RouteCollection.php#L239 ? should I change this line as well or will it break code for someone who doesn't use the default controller and use the odeprecated syntax?

**Comment by Selion05** [comment]
https://github.com/sonata-project/SonataAdminBundle/blob/57a4e6d4556dc4ac476b9658df66cb5e11174156/src/Command/GenerateAdminCommand.php#L128-L129

**Comment by phansys** [comment]
This issue was fixed by #5228.
Thank you!
