### ISSUE TITLE
Default value for filter

### ISSUE THREAD

**Issue by vazgen** [sonata-project/SonataAdminBundle#556]
Hello,

Is it possible to set default value for filter? I did not found in documentation as will as from source code analysis.

Thanks.

**Comment by webdevilopers** [comment]
@johnpez Just stumbled upon your issue.

When you submi the filters you will recognize that instead of a boolean true / false or 0 / 1 it will submit **1 for true** and **2 for false**.

These values relate to the class I referenced above:
https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/Type/EqualType.php

This should be the official solution:
```php
    public function getFilterParameters()
    {
        $this->datagridValues = array_merge(array(
                'enabled' => array (
                    'type'  => EqualType::TYPE_IS_EQUAL,
                    'value' => EqualType::TYPE_IS_EQUAL
                )
            ), $this->datagridValues);

        // Filter not displayed?
        $this->datagridValues = array_merge(array(
                'locked' => array (
                    'type'  => EqualType::TYPE_IS_EQUAL,
                    'value' => EqualType::TYPE_IS_NOT_EQUAL
                )
            ), $this->datagridValues);

        return parent::getFilterParameters();
    }
```

Correct, @pulzarraider ? I think these examples should be added to the docs too as suggested in https://github.com/sonata-project/SonataAdminBundle/issues/2529

**Comment by stetodd** [comment]
When I was trying to get this working I had to do the following:

```PHP
use Sonata\CoreBundle\Form\Type\EqualType;
use Sonata\CoreBundle\Form\Type\BooleanType;

public function getFilterParameters()
    {
        $parameters = parent::getFilterParameters();

        $parameters['completed'] = array (
            'type' => EqualType::TYPE_IS_EQUAL,
            'value' => BooleanType::TYPE_NO
        );

        return $parameters;
    }
```

Merging with `$this->datagridValues` didn't work as expected.

**Comment by Zuhayer** [comment]
This issue thread helped me. Thanks.

**Comment by ec-ecss** [comment]
Please how to do that in 2023 ?
The getFilterParameters is now final

**Comment by haivala** [comment]
just a guess but `configureFilterParameters`?
