### ISSUE TITLE
AdminLTE 3 implementation

### ISSUE THREAD

**Issue by muspelheim** [sonata-project/SonataAdminBundle#5597]
## Feature Request

Hi, are you planned to implement AdminLTE 3? it looks better than 2 and seems modern

https://adminlte.io/themes/dev/AdminLTE/index.html

**Comment by OskarStark** [comment]
No plans yet, but we would highly appreciate it 😍
@silasjoisten is currently working on implementing Webpack Encore in https://github.com/sonata-project/SonataAdminBundle/pull/5461

This should be done afterwards, maybe you can support him

**Comment by ElectricMaxxx** [comment]
Yeess. Just a quick win for now. -------- Originalnachricht --------Betreff: Re: [sonata-project/SonataAdminBundle] AdminLTE 3 implementation (#5597)Von: Oskar Stark An: sonata-project/SonataAdminBundle Cc: Subscribed No plans yet, but we would highly appreciate it 😍

@silasjoisten is currently working on implementing Webpack Encore in #5461

This should be done afterwards, maybe you can support him



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/sonata-project/SonataAdminBundle/issues/5597?email_source=notifications\u0026email_token=AAWFN2XRVFWWDHKQHNIZYXTP3OUQDA5CNFSM4HZVCBCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYF43CQ#issuecomment-504089994",

"url": "https://github.com/sonata-project/SonataAdminBundle/issues/5597?email_source=notifications\u0026email_token=AAWFN2XRVFWWDHKQHNIZYXTP3OUQDA5CNFSM4HZVCBCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYF43CQ#issuecomment-504089994",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by TangMonk** [comment]
cool

**Comment by wbloszyk** [comment]
Please reopen this issue. I will update AdminLte.

@silasjoisten Do you need help with Webpack? Are you still working on it?

**Comment by wbloszyk** [comment]
@OskarStark Also can You create new temporary branch from master? I think better way for review will be create seperate branch, adding changes in atomic commits and after all rebase it to master branch.

**Comment by OskarStark** [comment]
Sure I can, but we should merge Webpack integration first, should we?

**Comment by wbloszyk** [comment]
It will be nice if webpack is finished. If not i can update AdminLte(commits: upgrade vendor, update templates...) but after rebase result will be the same.

**Comment by wbloszyk** [comment]
@OskarStark 
We can push both features to temperary branch and after work done rebase it and marge to master. 

@sonata-project/contributors 
Like We wrote here:

> @OskarStark Also can You create new temporary branch from master? I think better way for review will be create seperate branch, adding changes in atomic commits and after all rebase it to master branch.

> Sure I can, but we should merge Webpack integration first, should we?

I check webpack. Last update was in 1 march 2020. I decide to help(or finish it) for @silasjoisten. Can i split it and push as atomic commits? Mark @silasjoisten as co-author will be enough? I dont wanna stealing his work.

Also today I should finish integrate AdminLTE 3 but is should be update after webpack to avoid unnesessery adding vendors.

**Comment by OskarStark** [comment]
@silasjoisten can you add @wbloszyk as maintainer to your fork?

**Comment by VincentLanglet** [comment]
Will close in favor of the discussion in https://github.com/sonata-project/SonataAdminBundle/issues/7156
