### ISSUE TITLE
Possible bug in FormMapper:add()

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataAdminBundle#6338]
SonataAdminBundle 3.75

We check current admin role to add form field in the end of resolving options.
I think we need do it in start of the add method.
Also field description adds always, but form field not. There second possible bug?

https://github.com/sonata-project/SonataAdminBundle/blob/87aa46124d2c5d35e243d912a6285bd21c43d86d/src/Form/FormMapper.php#L155-L159

**Comment by VincentLanglet** [comment]
Please fill the bug template.
- how do you reproduce the bug ?
- what behavior do you have ?
- what do you want to see ?

This issue seems only theorical

**Comment by kirya-dev** [comment]
> This issue seems only theorical

Yes it so. Me need more time to describe this fully. Its just discussion

**Comment by VincentLanglet** [comment]
> > This issue seems only theorical
> 
> Yes it so. Me need more time to describe this fully. Its just discussion

Hi, do you have any time to add more description ?
Without a real example/way to reproduce the bug, there is no real discussion and this issue will quickly be closed.

If you think that any changes should be done, you can also open a PR and add tests about this.

**Comment by kirya-dev** [comment]
What is reason add to form field description but not in form builder (if role check fails)?

**Comment by VincentLanglet** [comment]
> What is reason add to form field description but not in form builder (if role check fails)?

There are maybe not. But if there is no impact, it's not a bug.
And I don't think it leads to any bug since it's done this way for a long time.

If you look at the history, code was changed soon: https://github.com/sonata-project/SonataAdminBundle/commit/d21160a0f203d9c433e1ae7614525cb3a4d1f63b#diff-8617d89b3c98498bf8266160dce5d161
That's only thanks/because to this change that you find the situation as weird.

If I understand correctly, you want to change
````
        $this->admin->addFormFieldDescription($fieldName, $fieldDescription);

        if (!isset($fieldDescriptionOptions['role']) || $this->admin->isGranted($fieldDescriptionOptions['role'])) {
            $this->formBuilder->add($name, $type, $options);
        }
```
to
```
        if (!isset($fieldDescriptionOptions['role']) || $this->admin->isGranted($fieldDescriptionOptions['role'])) {
            $this->admin->addFormFieldDescription($fieldName, $fieldDescription);
            $this->formBuilder->add($name, $type, $options);
        }
```

You can check locally, open a PR, and add tests. That's the best way to discuss about this.
