### ISSUE TITLE
Bug in ModelChoiceLoader

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataAdminBundle#6517]
Hello every body. Im using sonata 3.77.

Im try configure form field with `ModelType`:
```php
        $discounts = [];

        //... some logic of adding discounts
    
        $formMapper->add('discount', ModelType::class, [
            'choices' => $discounts,
            'choice_label' => fn($choice, $id, $value) => $discounts[$id]->getName() . ' #' . $discounts[$id]->getId(),
        ]);
```

**Actual result:**
Get error **Undefined offset 1**

**Expected result:**
No errors. choice list is empty.

Im research this problem and found that sonata dont determine when im pass empty `choices` or no pass anyway.
Need change default value of option `choices` as `null`

And there change logic checking on not null on line 131 second condition
https://github.com/sonata-project/SonataAdminBundle/blob/d43224e0aa4e747631798b7816568c378d7ba668/src/Form/ChoiceList/ModelChoiceLoader.php#L126-L135

**Comment by kirya-dev** [comment]
This works perfectly for me:
https://github.com/sonata-project/SonataAdminBundle/pull/6548

**Comment by phansys** [comment]
I don't understand the issue, and I can't reproduce it locally (in my case, regardless I use `'choices' => []`, the model is filled with the values from my model when using `ModelType` instead of `ChoiceType`). 
Where is the error thrown? Could you please use the [issue template](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/.github/ISSUE_TEMPLATE/Bug.md) to report the problem, including the stack trace?

Thank you!

**Comment by kirya-dev** [comment]
> in my case, regardless I use `'choices' => []`, the model is filled with the values from my model when using `ModelType` instead of `ChoiceType`

problem in this. `'choices' => []` mustn't loads entities. should empty because you pass empty - it more truth
