### ISSUE TITLE
generateUrl is now final and can't be overridden

### ISSUE THREAD

**Issue by tbyte80** [sonata-project/SonataAdminBundle#7441]
First and foremost thank you for your great work!

In some of my Admin classes I override the method  `generateUrl` which is now final and can't be done anymore.

I want to prefill some form elements when creating a new Entity based on the current filter settings of the user.

```php
public function generateUrl($name, array $parameters = [], $absolute = RoutingUrlGeneratorInterface::ABSOLUTE_PATH)
{
    if($name == 'create') {
        $parameters = $this->getFilterParameters();
    }
    return parent::generateUrl($name, $parameters, $absolute);
}

 public function getNewInstance()
    {
        $scriptGroup= $this->request->query->get('scriptGroup');
        $sgid = $scriptGroup ? $scriptGroup['value'] : 3;
        /** @var Script $obj */
        $obj = parent::getNewInstance();
        $em = $this->getConfigurationPool()->getContainer()->get('doctrine')->getManager();
        /** @var ScriptGroup $sg */
        $sg = $em->getRepository(ScriptGroup::class)->find($sgid);
        $obj->setScriptGroup($sg);

        return $obj;
    }
```
That way I can create a custom "create URL" where I can access certain parameters and initialize my entity.

P.S. I am in a migration process. I know that I cannot get Container and doctrine the way I do it above anymore. I haven't researched yet how to do it now.

**Comment by VincentLanglet** [comment]
The implementation of the `generateUrl` is
```
final public function generateUrl(string $name, array $parameters = [], int $referenceType = RoutingUrlGeneratorInterface::ABSOLUTE_PATH): string
    {
        return $this->getRouteGenerator()->generateUrl($this, $name, $parameters, $referenceType);
    }
```

So instead of overriding the `AdminInterface::generateUrl`, you can implement you custom `RouteGeneratorInterface`.

**Comment by tbyte80** [comment]
Sure I could do that. But how do I achieve that method being called by CRUDController when creating object urls?

**Comment by VincentLanglet** [comment]
> Sure I could do that. But how do I achieve that method being called by CRUDController when creating object urls?

Currently, the CRUDController use `AdminInterface::generateUrl` so you have nothing more to.
The Admin is just delegating the call to the `RouteGeneratorInterface`.

**Comment by tbyte80** [comment]
Thank you for your advice and sorry for the misunderstanding (and for opening a new issue - I could have sworn there was no comment box below when I looked into this issue last time).

Your proposed solution works - still, I think it is inconvenient and bulky. Since `DefaultRouteGenerator` is final as well, I have to copy paste everything to a new class implementing `RouteGeneratorInterface`, make my little change and pass it to the Admin class. This applies to every Admin class that incorporates little adjustments of that kind. 

Sure, I can have my own `AbstractRouteGenerator` and extend it every time - but that basically requires having a circular dependency back to the Admin class, since information from Admin class is needed most of the time (e.g.  `getFilterParameters`).
So it's bulky and a maintenance overhead (if `DefaultRouteGenerator` changes, those changes should be applied to that custom class).

What's the gain of that? I understand that `generateUrl` and other methods don't do much and basically just forward parameters to other modules but having those method calls on the admin class directly allows convenient customization without much hassle. I still don't get why you want to take that convenience away?

**Comment by VincentLanglet** [comment]
> Your proposed solution works - still, I think it is inconvenient and bulky. Since `DefaultRouteGenerator` is final as well, I have to copy paste everything to a new class implementing `RouteGeneratorInterface`, make my little change and pass it to the Admin class. This applies to every Admin class that incorporates little adjustments of that kind.
> Sure, I can have my own `DefaultRouteGenerator` and extend it every time - but that basically requires having a circular dependency back to the Admin class, since information from Admin class is needed most of the time (e.g. `getFilterParameters`).

You don't have to, there is multiple solution to that:
- Service decoration https://symfony.com/doc/current/service_container/service_decoration.html
- Or simply injecting the basic service in the constructor and then you could write
```
public function foo() {
    return $this->defaultService->foo();
}
```

> So it's bulky and a maintenance overhead.

If you think it's a maintenance overhead to maintain one class, please thinks about it for a well-used repository ;)

> What's the gain of that? I understand that `generateUrl` and other methods don't do much and basically just forward parameters to other modules but having those method calls on the admin class directly allows convenient customization without much hassle. I still don't get why you want to take that convenience away?

It's not because it seemed easier for you before, that it really was ; and it's not because it seemed easier it was a good practice. There is already tons of article (like https://matthiasnoback.nl/2018/09/final-classes-by-default-why/) explaining that.

Let's make short here:
- We have interface for abstraction
- We have some implementation we rely on, making a class final allow us to do more change in our code without calling it a BC-break.
- In the same way, abstract classes are relying on some method implementation, so it make sens to declare then final. Plus it allows us to change more easily the code without introducing BC-break.
- Making things `@internal` is not the solution. An `@internal` method MUST NOT be used by another developer. A final method can be used.
- We've been sure there was always an alternative when declaring a method final. When there was not, we added some "configureMethod" for exemple. Defining those methods `final` helps us to detect those situations.
- We may split the AbstractAdmin into (more) smaller service and those one line methods could be deprecated in favor of using the service directly.

**Comment by tbyte80** [comment]
You are right. I agree that moving from inheritance to composition is a good design choice in general and making things final faciliates maintenance a lot on your side.
Thanks for being explicative and patient. Pointing me to the decorator pattern was a good hint, didn't think about it. It's a solution I am happy with! Merci :) .
