### ISSUE TITLE
Using Label from Configuration 

### ISSUE THREAD

**Issue by axzx** [sonata-project/SonataAdminBundle#7475]
## Feature Request

![obraz](https://user-images.githubusercontent.com/1436016/132305318-a2cbd99d-a5e5-4347-84cf-467efd2fd2a8.png)

What is the Label in the configuration for?
From what I can see it's used in the left main menu.

It is not used in breadcrumb. The getClassnameLabel method is used there.

In my opinion, Label should be used to a greater extent.
This will make it easier to change texts on the page. 

It will be of great help in my case.
I have 2 admins with one entity. 
![obraz](https://user-images.githubusercontent.com/1436016/132305987-dcbd3c86-3191-48cc-9a26-5aeccc939225.png)

**Comment by VincentLanglet** [comment]
The label (and the group option) is used for the title of the admin in the left side-bar.

Seems like the breadcrumb label is generated with
- The `getClassNameLabel()`
- The action
It makes more sens that just using the `label` because you might want different label for different action.

Plus changing the strategy would be a BC-break and is not possible now the 4.0 is released.

Using different breadcrumb label for different admin with the same entity is already possible.
The `$classnameLabel` property of the `AsbtractAdmin` is a protected property, so you can override it in your admin.
This allow you to have different classnameLabel for the two different admins.

**Comment by VincentLanglet** [comment]
I consider the issue solved since a solution was proposed. (classnameLabel)
