### ISSUE TITLE
Revert AbstractAdmin->getParentAssociationMapping() To Not Final

### ISSUE THREAD

**Issue by djpretzel** [sonata-project/SonataAdminBundle#7494]
## Feature Request

I have noticed that in 4.0 AbstractAdmin->getParentAssociationMapping() has been marked as final, but this appears to prevent the following use case:

- I have an "AbstractImageAdmin" that I store common code for different types of concrete ImageAdmin classes
- An ImageAdmin is always the child of a given concrete class, i.e. "GameImageAdmin", "ArtistImageAdmin", etc.
- Now I have no means of overriding and having a reusable abstract admin of my own?

```
abstract class AbstractImageAdmin extends AbstractModelAdmin
{
    protected $datagridValues = [
        '_sort_by' => 'id',
        '_sort_order' => 'DESC',
    ];

    public function getParentAssociationMapping() {
        return $this->getParentEntityName();
    }

    abstract protected function getParentEntityName();
```

...is there a different way of accomplishing the same code reuse with 4.0? I've been following a lot of the changes and while I understand the desire to mark things as final to prevent confusion, it seems like our ability to create usable abstract admins is diminished?

**Comment by VincentLanglet** [comment]
You're not fully exposing your issue, since the code you provide is just renaming the method without giving the implementation.

There is no need to override this method, and if you need it, it certainly can be done differently since the parent association mapping is not supposed to be touch. Try removing the override or tell us more about the override you do.

I personally use tons of abstract classes without any issues.
You should also take a look at AdminExtension since it's supposed to be the right way to share logic between different admin classes.

**Comment by djpretzel** [comment]
As you suggested, I tried removing the override, and it didn't seem to break anything obvious... I can only assume I'd added it to accomplish something in 3.x that might not be necessary in 4.x, but either way you're right, it doesn't seem like the method needs to be open
