### ISSUE TITLE
Open Source version of sonata project

### ISSUE THREAD

**Issue by grekpg** [sonata-project/SonataAdminBundle#7627]
Why many functions as marked as final ? 
You planing share open version of sonata project for developers ? (final functions are for consumers)
I have many overrided methods why is a reason to mark functions as final for open source library ? 

Example i add few list modes but want in admin extension remove few. 
Is not possible - because AbstractAdmin - > setListModes is final !!! shit

**Comment by core23** [comment]
> Why many functions as marked as final ?

Because this will help us to maintain this project, especially the stable versions.

> You planing share open version of sonata project for developers ? (final functions are for consumers)

No, but feel free to open special methods if you can provide a valid use case that requires a more open API.

**Comment by VincentLanglet** [comment]
> Why many functions as marked as final ?

Because it's easier to maintain. And, as far, there is always another way to override something, with injection/composition or by calling some setters.

> You planing share open version of sonata project for developers ? (final functions are for consumers) I have many overrided methods why is a reason to mark functions as final for open source library ?

Open source libraries can have final method.
 
> Example i add few list modes but want in admin extension remove few. Is not possible - because AbstractAdmin - > setListModes is final !!!

It would require more explanation to prove that the behavior you're looking for is not possible. In my own project I override tons of things and still found way to do it with the final methods.

> shit

Thanks for the consideration you have for the work of the maintainers who maintain on their free time this ready-to-use library. You can still fork it or implement your own library.

Anyway, I'm closing this, as the final keyword won't be removed.

**Comment by grekpg** [comment]
what is diffrence between protected and final in authors developing ? 

When I create class extends and override method this is my problem not Your. I create full ajax version (sonata rerurn json files for list) many view modes - more than crud, integrate MDB front,  public interface for users with edit. So i realy need override methods. 

modern ways is inferfaces , return values but not final method for framework app....

I have many thanks for authors for makking this application. But realy i dont understand why you close ways to make own modifications.

**Comment by core23** [comment]
> what is diffrence between protected and final in authors developing ?

https://matthiasnoback.nl/2018/09/final-classes-by-default-why/
