### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by BenPoell** [sonata-project/SonataAdminBundle#7652]
Hi,

I just wanted to check the newest version of Sonata Admin but it seems that the demo environment does not work :( 
![image](https://user-images.githubusercontent.com/24900930/145825320-843310af-c232-4fe2-82c7-3dc8c78b4820.png)

Best regards,
Benjamin

**Comment by VincentLanglet** [comment]
Hi.

The demo (which wasn't using the last version of Sonata at all) is unmaintained for at least 6 months now.
And I don't think it will change soon.

The error you get is the same than for https://sonata-project.org/, the SSL certificate is invalid.
Since we moved the docs to https://docs.sonata-project.org/, I don't know if the old website (which was in Symfony 2) is worth to be maintained too.
