### ISSUE TITLE
The demo is broken

### ISSUE THREAD

**Issue by php4fan** [sonata-project/SonataAdminBundle#7717]
From the docs:
https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/

I followed the link very near the top to the demo: 
https://demo.sonata-project.org/

I get this page:

![image](https://user-images.githubusercontent.com/13969584/151818596-b49f2c3e-efd7-4a83-8e16-174988a136a3.png)

So I click on "Launch your container".

Then I get this page for a few seconds:

![image](https://user-images.githubusercontent.com/13969584/151818685-199ada70-bce0-4c92-93c6-2b534792955e.png)

and then it goes back to the previous one.

And so on.

**Comment by VincentLanglet** [comment]
@sonata-project/contributors The demo is, not maintained and not working for months.
I think we should 
- remove it from docs
- shut down the url

WDYT ?

**Comment by jordisala1991** [comment]
There are some placed where we are referencing it:

https://docs.sonata-project.org/projects/SonataSeoBundle/en/3.x/reference/sitemap/?highlight=sandbox#configuration-example
https://docs.sonata-project.org/projects/SonataClassificationBundle/en/3.x/reference/classification_types/?highlight=demo#category
https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/?highlight=demo#admin-bundle

Also in the ecommerce docs, the demo word appears sometime, found by searching on main docs:

https://docs.sonata-project.org/en/master/search/?q=demo&check_keywords=yes&area=default

To me I would kill the link references, and don't care about the ecommerce docs because it is deprecated.

**Comment by VincentLanglet** [comment]
I've opened the PR to remove every mentions
