### ISSUE TITLE
Admin registration via arguments is not working since 4.22

### ISSUE THREAD

**Issue by jgrygierek** [sonata-project/SonataAdminBundle#8066]
Hi, it is a bug or a feature? I tried to run my code and it works only when admin is defined via tags. Defining it via arguments is not working anymore.

I got:
```
[error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/..."" at /var/www/sonata-test-bundle/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127
```

**Comment by jgrygierek** [comment]
Bump?

**Comment by jordisala1991** [comment]
Can you track down which PR caused the problem? That would make it easier to solve.

**Comment by jgrygierek** [comment]
@jordisala1991 https://github.com/sonata-project/SonataAdminBundle/pull/7964

I tested it using my own package: https://github.com/jgrygierek/SonataBatchEntityImportBundle

**Comment by jordisala1991** [comment]
Maybe you can help us debugging @VincentLanglet . I will try to test it too.

**Comment by VincentLanglet** [comment]
Kinda surprising it's related to the https://github.com/sonata-project/SonataAdminBundle/pull/7964 PR since I only touched the ExtensionCompilerPass. This issue lacks of information. What are all the symfony/sonata versions used ? Where does come from the route requested ? A reproducer would be nice.

Because if it would have break admin registration with arguments:
- Some tests would fail
- I would expect more issues created

Also, like in other compilerPass, I still fetch data from arguments:
https://github.com/sonata-project/SonataAdminBundle/pull/7964/files#diff-3093ab12e2b0ed12756607edace790fe1d4dc1e9bbacb07bc4becac405791dbdR115

**Comment by jgrygierek** [comment]
@VincentLanglet it stopped working in versions higher than `"sonata-project/admin-bundle": "4.21.*",`

**Comment by VincentLanglet** [comment]
> @VincentLanglet it stopped working in versions higher than `"sonata-project/admin-bundle": "4.21.*",`

Yes, maybe but if you bumped from 4.21.* to 4.26, it can be any minor between.
If you bumped to 4.22.*, it can be any patch.

Does it stop with 4.22.0 ? Does other package were bumped too ?
Without a specific composer diff, it could be anything ; that why issues have template

<details>
<summary>show</summary>

#### Sonata packages

<p>

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```

</p>

#### Symfony packages

<p>

```
$ composer show --latest 'symfony/*'
# Put the result here.
```
</details>

And as I said, more than tracking the specific PR, a reproducer would be better because
- ""No route found for "GET http://localhost/...""" is not enough, we don't even know which route is causing the issue
- You talked about https://github.com/jgrygierek/SonataBatchEntityImportBundle, maybe the issue is in it
- Test are working fine on https://github.com/sonata-project/SonataAdminBundle/pull/8089 (it fails only because of deprecations) but route are found
- I'm in touch with two companies using latest version without any issue

With the few information I have so far, I can do nothing, because I saw no bug :/

**Comment by jgrygierek** [comment]
Yes, I checked it on 4.22.0 and it was not working anymore. As I remember only sonata was updated.
