### ISSUE TITLE
Please tag a release for latest commit in 3.x branch

### ISSUE THREAD

**Issue by andrew-demb** [sonata-project/SonataAdminBundle#8185]
## Feature Request

One merged PR in the `3.x` branch fixed PHP 8.1 deprecations - https://github.com/sonata-project/SonataAdminBundle/pull/7818 are left without tagged release.

This tag simplifies us to continue step-by-step upgrades of our application dependencies with clearing deprecations in the process - please tag a release of `3.107.4` on the latest `3.x` branch commit - https://github.com/sonata-project/SonataAdminBundle/commit/8ff82e4e243d3f7b3f9186fb04a9cadb37f1bd15.

**Comment by andrew-demb** [comment]
In addition - seems like branch `3.x` is not fully merged with the current main one `4.x` - https://github.com/sonata-project/SonataAdminBundle/compare/3.x

![image](https://github.com/sonata-project/SonataAdminBundle/assets/12499813/44661ef7-4bac-4c2a-83bf-1e289166d19e)

**Comment by VincentLanglet** [comment]
These changes are not needed in 4.x where we already use typehint in the 4.x branch and there is no deprecation.

And you don't need a tag to use a branch ; you can target 3.x directly.

**Comment by andrew-demb** [comment]
Yes, I agree - I can.
But it will be clear for all to have a last 3.x tag with already merged to 3.x commits.

If you don't want to tag , I will stick with installation from the branch - I'm OK with it

**Comment by VincentLanglet** [comment]
> If you don't want to tag , I will stick with installation from the branch - I'm OK with it

Honestly since:
- It's "only" deprecations
- 3.x branch can be used
- The problem wasn't reported until now
- You're ok with it

I think it's better to not create a release. But it's debatable.

The latest 3.x release was released more than one year ago https://github.com/sonata-project/SonataAdminBundle/releases/tag/3.107.3 and I dunnot want people to believe this branch is still maintained.

I want people to move on 4.x branch, there is still to many using the 3.x one https://packagist.org/packages/sonata-project/admin-bundle/stats
